apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simple-expressjs-app-deployment
  labels:
    app: simple-expressjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-expressjs-app
  template:
    metadata:
      labels:
        app: simple-expressjs-app
    spec:
      containers: 
      -  name: simple-expressjs-app
         image: sohaibm/simple-expressjs-app
         ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: simple-expressjs-app-service
spec: 
  selector: 
    app: simple-expressjs-app
  type: 
    LoadBalancer
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
